version: 1

repository:
  name: ai-claims-processing-platform

artifacts:
  - name: gateway-service
    type: gateway
    project: services/gateway-service/GatewayService.API
    dockerfile: services/gateway-service/GatewayService.API/Dockerfile

    dependencies: []

  - name: claims-service
    type: api
    project: services/claims-service/ClaimsService.API
    dockerfile: services/claims-service/ClaimsService.API/Dockerfile

    dependencies:
      - building-blocks/contracts

  - name: document-service
    type: api
    project: services/document-service/DocumentService.API
    dockerfile: services/document-service/DocumentService.API/Dockerfile

    dependencies:
      - building-blocks/contracts

  - name: notification-service
    type: worker
    project: services/notification-service/NotificationService.API
    dockerfile: services/notification-service/NotificationService.API/Dockerfile

    dependencies:
      - building-blocks/contracts

  - name: fraud-service
    type: worker
    project: services/fraud-service/FraudService.API
    dockerfile: services/fraud-service/FraudService.API/Dockerfile

    dependencies:
      - building-blocks/contracts

  - name: payment-service
    type: worker
    project: services/payment-service/PaymentService.API
    dockerfile: services/payment-service/PaymentService.API/Dockerfile

    dependencies:
      - building-blocks/contracts

  - name: document-processor
    type: function
    project: serverless/document-processor-function