version: 1

repository:
  name: ai-claims-processing-platform

artifacts:
  - name: gateway-service
    type: gateway
    root: services/gateway-service
    entryPoint: services/gateway-service/GatewayService.API
    dockerfile: services/gateway-service/GatewayService.API/Dockerfile

    dependencies:
      - services/claims-service/ClaimsService.API
      - services/document-service/DocumentService.API
      - services/customer-service/CustomerService.API
    ignoredPaths:
      - GatewayService.API/Properties
      - GatewayService.API/obj
      - GatewayService.API/bin

  - name: claims-service
    type: api
    root: services/claims-service
    entryPoint: services/claims-service/ClaimsService.API
    dockerfile: services/claims-service/ClaimsService.API/Dockerfile

    dependencies:
      - building-blocks/contracts
    ignoredPaths:
      - ClaimsService.API/Properties
      - ClaimsService.API/obj
      - ClaimsService.API/bin

  - name: document-service
    type: api
    root: services/document-service
    entryPoint: services/document-service/DocumentService.API
    dockerfile: services/document-service/DocumentService.API/Dockerfile

    dependencies:
      - building-blocks/contracts
    ignoredPaths:
      - DocumentService.API/Properties
      - DocumentService.API/obj
      - DocumentService.API/bin

  - name: notification-service
    type: worker
    root: services/notification-service
    entryPoint: services/notification-service/NotificationService.API
    dockerfile: services/notification-service/NotificationService.API/Dockerfile

    dependencies:
      - building-blocks/contracts
    ignoredPaths:
      - NotificationService.API/Properties
      - NotificationService.API/obj
      - NotificationService.API/bin

  - name: fraud-service
    type: worker
    root: services/fraud-service
    entryPoint: services/fraud-service/FraudService.API
    dockerfile: services/fraud-service/FraudService.API/Dockerfile

    dependencies:
      - building-blocks/contracts
    ignoredPaths:
      - FraudService.API/Properties
      - FraudService.API/obj
      - FraudService.API/bin

  - name: payment-service
    type: worker
    root: services/payment-service
    entryPoint: services/payment-service/PaymentService.API
    dockerfile: services/payment-service/PaymentService.API/Dockerfile

    dependencies:
      - building-blocks/contracts
    ignoredPaths:
      - PaymentService.API/Properties
      - PaymentService.API/obj
      - PaymentService.API/bin

  - name: customer-service
    type: api
    root: services/customer-service
    entryPoint: services/customer-service/CustomerService.API
    dockerfile: services/customer-service/CustomerService.API/Dockerfile

    dependencies: []
    ignoredPaths:
      - CustomerService.API/Properties
      - CustomerService.API/obj
      - CustomerService.API/bin

  # Will work on fucntion app deployment automation later
  # - name: document-processor
  #   type: function
  #   root: serverless/document-processor-function
  #   entryPoint: serverless/document-processor-function