global:
  scrape_interval: 30s

scrape_configs:

  - job_name: "claims-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["claims-api:8080"]

  - job_name: "notification-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["notification-api:8080"]