// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolicyService.Infrastructure.Persistence;

#nullable disable

namespace PolicyService.Infrastructure.Persistence.Migrationscls
{
    [DbContext(typeof(PolicyDbContext))]
    partial class PolicyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolicyService.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("PolicyTypeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyTypeDefinitionId");

                    b.ToTable("policies", (string)null);
                });

            modelBuilder.Entity("PolicyService.Domain.Entities.PolicyTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedVehicleTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaximumClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("policy_type_definitions", (string)null);
                });

            modelBuilder.Entity("PolicyService.Domain.Entities.Policy", b =>
                {
                    b.HasOne("PolicyService.Domain.Entities.PolicyTypeDefinition", null)
                        .WithMany()
                        .HasForeignKey("PolicyTypeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PolicyService.Domain.Entities.Vehicle", "Vehicle", b1 =>
                        {
                            b1.Property<Guid>("PolicyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("RegistrationNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("VehicleType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("PolicyId");

                            b1.ToTable("policies");

                            b1.WithOwner()
                                .HasForeignKey("PolicyId");
                        });

                    b.Navigation("Vehicle")
                        .IsRequired();
                });

            modelBuilder.Entity("PolicyService.Domain.Entities.PolicyTypeDefinition", b =>
                {
                    b.OwnsMany("PolicyService.Domain.Entities.Coverage", "Coverages", b1 =>
                        {
                            b1.Property<Guid>("PolicyTypeDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("CoverageLimit")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PolicyTypeDefinitionId", "Id");

                            b1.ToTable("PolicyTypeDefinitionCoverages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PolicyTypeDefinitionId");
                        });

                    b.Navigation("Coverages");
                });
#pragma warning restore 612, 618
        }
    }
}
