name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - run: pwd
        run: ls -la
        run: whoami
        run: uname -a

      # - name: Checkout repository
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 2

      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: 10.0.x

      # - name: Restore
      #   run: dotnet restore platform/deployment/Deployment.Platform.Console

      # - name: Build
      #   run: dotnet build platform/deployment/Deployment.Platform.Console --configuration Release --no-restore

      # - name: Azure Login
      #   uses: azure/login@v2
        # with:
        #   client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #   tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #   subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Deploy
      #   run: |
      #     dotnet run \
      #       --project platform/deployment/Deployment.Platform.Console \
      #       -- deploy \
      #       --strategy impacted \
      #       --target AzureContainerApps \
      #       --environment dev \
      #       --base ${{ github.event.before }} \
      #       --head ${{ github.sha }}